# File: .github/workflows/publish.yml
name: publish-to-github-pages
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      kroki:
        image: yuzutech/kroki
        ports:
          - 8000:8000
        env:
          KROKI_MAX_URI_LENGTH: 64000
          KROKI_MERMAID_HOST: mermaid
          KROKI_EXCALIDRAW_HOST: excalidraw
      mermaid:
        image: yuzutech/kroki-mermaid
      excalidraw:
        image: yuzutech/kroki-excalidraw

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v6
        with:
          static_site_generator: next

      - name: Build Marp slides 🎞️
        run: npm run build:slides

      - name: Build with Next.js 🏗️
        run: npx next build

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
